### ISSUE TITLE
Make VNG API Common Django 3.2 compatible 

### ISSUE THREAD

**Issue by ahmadpoorgholam** [VNG-Realisatie/vng-api-common#190]
Currently vng api common is pinned to < Django 3.0, but 2.2 is end of life in April this year and this library currently blocks upgrading CMIS adapter and Open Zaak to 3.2 LTS.

**Tasks**

- [ ] Update the `tox.ini` envlist to support the following matrix of versions
    - Python 3.7 - Django 2.2
    - Python 3.8 - Django 2.2
    - Python 3.7 - Django 3.2
    - Python 3.8 - Django 2.2
- [ ] Update the Github CI workflow to support the same matrix
- [ ] Make the necessary changes to the package to support Django 3.2
- [ ] Update the package metadata to correctly reflect the supported versions
- [ ] Extra: see if we can add Python 3.9 and Python 3.10 support
